### ISSUE TITLE
VTS browser for the latest versions of Mac OS.

### ISSUE THREAD

**Issue by SukanyaGavhane** [melowntech/vts-browser-cpp#10]
We observed that the latest versions of **Mac OS**(Ex: Mojave) deprecates **OpenGL** and must have **Metal** to provide graphics hardware support. 

Considering that we have following queries,

**1. Does the latest version of the VTS browser provide support for an updated Mac OS versions ?** 

**2. The latest version of VTS for Mac OS is developed based on OpenGL or Metal?**
 
 **3. If it is based on Metal, does it provide any leverage for OpenGL?**

**Comment by SukanyaGavhane** [comment]
Hello Tomas,
Sorry for posting the same question again.

We have decided to use VTS as a GIS tool for our desktop application, but the support on macOS is one of the crucial points.

This is quite an urgent requirement and your inputs will help us make better decisions.

**Comment by SukanyaGavhane** [comment]
Hello Tomos,
Sorry to bother you, but this is quite an urgent requirement and Mac OS support is really a crucial point for us to finalize VTS as a GIS tool.

We are trying to setup VTS on MacOS(tried on Mojave & Catalina), but the cmake is getting crashed while configuring.

Please let us know whether VTS is supported on Mac OS or not? If yes, could you please specify versions of macOS and other supporting tools that are required?


Any inputs would be really appreciated!

**Comment by malytomas** [comment]
Hello SukanyaGavhane,

First of all, please understand, that this is an issue reporting tool, not an instant messaging. I will give you a comprehensive answer when I have it - I have to discuss it with my colleagues first. Avoiding empty answers keeps it more readable for others who might have the same or similar issue later.

A quick answer is that deprecation is not removal and it should be working for now.

----

> We are trying to setup VTS on MacOS(tried on Mojave & Catalina), but the cmake is getting crashed while configuring.

Please open another issue for this and provide all details you can.

**Comment by malytomas** [comment]
Hi SukanyaGavhane,

The current implementation is based on opengl only, but the browser is designed to have a rendering api agnostic part and a renderer, therefore it is possible to write your own renderer based on any other technology.

I can confirm now, that we will maintain support for apple devices even after they actually remove opengl. However, the technical details are not currently decided.

When apple does remove opengl, we will implement a new complementary renderer that works on macos/ios, but not necessarily metal.

Let me know if this answers your question.

**Comment by SukanyaGavhane** [comment]
Hello Tomas,

 Yes, this is useful.
Thank you so much for the information that you have shared .
