### ISSUE TITLE
Cmake crash during VTS setup

### ISSUE THREAD

**Issue by SukanyaGavhane** [melowntech/vts-browser-cpp#11]
1.
[CMakeError.log](https://github.com/melowntech/vts-browser-cpp/files/4645952/CMakeError.log)
	We are trying to setup VTS on MacOS (tried on Mojave & Catalina), but the **cmake is getting crashed while configuring** in CmakeError.log file we are getting following error.

_"Build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_9581d.build/Objects-normal/x86_64/HAVE_JNI_H.dia -c /Users/ncircletech/Desktop/Sukanya/GitRepository/VTS\ Build/CMakeFiles/CheckIncludeFiles/HAVE_JNI_H.c -o /Users/ncircletech/Desktop/Sukanya/GitRepository/VTS\ Build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_9581d.build/Objects-normal/x86_64/HAVE_JNI_H.o
/Users/ncircletech/Desktop/Sukanya/GitRepository/VTS Build/CMakeFiles/CheckIncludeFiles/HAVE_JNI_H.c:2:10: fatal error: 'jni.h' file not found
#include <jni.h>
       
1 error generated.

** BUILD FAILED **

the following build commands failed:
    CompileC CMAKE_TRY_COMPILE.build/Debug/cmTC_9581d.build/Objects-normal/x86_64/HAVE_JNI_H.o /Users/ncircletech/Desktop/Sukanya/GitRepository/VTS\ Build/CMakeFiles/CheckIncludeFiles/HAVE_JNI_H.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
"_
•	**For more details I have attached cmake crash log file with this query.**

2.	Also we have tried to **setup VTS through cmd**,
     •	While performing the same we got following error,
     _CMake Error at externals/browser/browser/CMakeLists.txt:9 (include):
      include could not find load file:
      buildsys/cmake/buildsys.cmake 
     CMake Error at externals/browser/browser/CMakeLists.txt:10 (enable_hidden_visibility):
      Unknown CMake command "enable_hidden_visibility"._

  So can you please suggest any guidelines on this?
  Any inputs would be really appreciated!

**Comment by vaclavblazek** [comment]
Did you clone the repository recursively? I.e. do you have checked out submodules?

**Comment by SukanyaGavhane** [comment]
Yes. We have clone the repository recursively and also we have check the submodules.

**Comment by malytomas** [comment]
Please create a new empty folder and run the following script in it:
```bash
(
echo "versions:" &&
sw_vers &&
git --version &&
cmake --version &&
clang --version &&
echo "git:" &&
git clone https://github.com/melowntech/vts-browser-cpp-build-wrapper.git vts-builder &&
cd vts-builder &&
git submodule update --init --recursive &&
echo "ls:" &&
ls -l externals/browser/browser/buildsys/cmake &&
echo "build" &&
mkdir build &&
cd build &&
cmake -DCMAKE_BUILD_TYPE=DEBUG ..
) 2>&1 | tee vts-build-output.txt
```

Afterwards, post here the file vts-build-output.txt.

Thanks.

**Comment by SukanyaGavhane** [comment]
Hello tomas,
Thank you so much for your feedback.

I have attached **vts-build-output.txt file.**
Kindly check  and let me know your comments on this.
[vts-build-output.txt](https://github.com/melowntech/vts-browser-cpp/files/4651343/vts-build-output.txt)

**Comment by malytomas** [comment]
Do you have somehow nonstandard configuration of new lines? I do not understand how all the 'command not found' has got there.

Anyway, it has corrupted the last command, so please go into the vts-builder folder and run the following command:
```bash
rm -R build && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=DEBUG .. 2>&1 | tee vts-build-output-2.txt
```
Be warned that the command starts with removing a folder - double check where you are running it.

Afterwards, post the new vts-build-output-2.txt file.

Thanks.

**Comment by SukanyaGavhane** [comment]
Hello tomas,
Thank you so much for your quick feedback.

I have attached  **vts-build-output-2.txt**.
Kindly check and let me know your comments on this.
[vts-build-output-2.txt](https://github.com/melowntech/vts-browser-cpp/files/4651576/vts-build-output-2.txt)

**Comment by malytomas** [comment]
Awesome,

just run this in the same folder as previously:
```bash
rm -R build && mkdir build && cd build && cmake -GXcode .. 2>&1 | tee vts-build-output-3.txt
```

This will generate xcode project instead of a makefile.

**Comment by SukanyaGavhane** [comment]
Hello Tomas,

Thank you so much for your support.
With the help of this i am able to generate and build the project .

Also i am not able to understand what is the exact reason to crash Cmake UI?
 is this to be built using commandline only ? is it a bug on Cmake side?

Do you have any inputs on it ?
If so it will be helpful for further development.

**Comment by malytomas** [comment]
Based on this:
```
CMake Error at externals/browser/browser/CMakeLists.txt:9 (include):
include could not find load file:
buildsys/cmake/buildsys.cmake
```
I suspect that you, indeed, had incorrectly cloned the repository, or that some symlinks have got corrupted, but I cannot say for sure.

Cmake Gui should work. But I never tried it.

Perhaps you can try to clone the repository the same way as in the script I send you, in some another new folder, and try the cmake gui again.
