### ISSUE TITLE
What is the standard unit used for altitude?

### ISSUE THREAD

**Issue by shrikant-panchal** [melowntech/vts-browser-cpp#12]
As per the geojson standards, the unit of altitude is in **meters** in geospatial co-ordinates.

We have realtime data of some geolocations including altitude in meters, how can we accurately place it in 3D space?

Does **navToPhys**(vts-browser-cpp) or **convertcoordsNavToPhys**(vts-browser-js) expects the altitude in meters or in some other units?

**Comment by malytomas** [comment]
Navigation SRS is defined in the mapconfig.
The referenceFrame->model->navigationSrs is the name of the SRS, which is used as a key into the table in srses.
These definitions contain both horizontal and vertical components, including the datum.

The geographic-wgs84, which is most commonly used in navigation srs, uses degrees for horizontal and meters above ellipsoid for vertical component.

**Comment by shrikant-panchal** [comment]
Thanks Tomos!
I was using ASL data instead of AGL.
AGL data for altitude gave me acceptable results.
