### ISSUE TITLE
The cache path cannot be changed

### ISSUE THREAD

**Issue by ExploreWilder** [melowntech/vts-browser-cpp#17]
Hi,

I try to change the cache path with `vts::MapCreateOptions::cachePath`. https://github.com/melowntech/vts-browser-cpp/blob/24668af213676db79913b8c595c1b418360f3a6b/browser/src/vts-libbrowser/include/vts-browser/mapOptions.hpp#L53

Here you can see where I set the cachePath: https://github.com/ExploreWilder/qmapshack/blob/bdc58a9995ce2d87aecc081d2c34264225122944/src/qmapshack/3d/C3DMap.cpp#L121

The option does not seem to be implemented. I cannot find where the _root_ path is changed. https://github.com/melowntech/vts-browser-cpp/blob/24668af213676db79913b8c595c1b418360f3a6b/browser/src/vts-libbrowser/resources/cache.cpp#L246

Thanks for your help,

Cheers,
Clement

**Comment by malytomas** [comment]
Hi,

this should be fixed in https://github.com/melowntech/vts-browser-cpp/commit/d8111d02b804b36da1fea29898b049cb861e1dfa now.

Thanks for the report.

**Comment by ExploreWilder** [comment]
Hi Tomáš,

I confirm. Thanks for the update.

Have a great day!
