### ISSUE TITLE
make not working on build

### ISSUE THREAD

**Issue by danammeansbear** [melowntech/vts-browser-cpp#5]
pc@pc:~/vts-browser-cpp/browser$ make -j4
* Building in build
CMake Error at cmake/buildsys_initial_validation.cmake:4 (message):
  CMAKE_BUILD_TYPE is not set.
Call Stack (most recent call first):
  CMakeLists.txt:4 (include)

-- Configuring incomplete, errors occurred!
See also "/home/pc/vts-browser-cpp/browser/build/CMakeFiles/CMakeOutput.log".
Makefile:23: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by danammeansbear** [comment]
I started on a fresh install of ubuntu to try and build some backend and front end projects so i can use this stack in unity but im not sure what im doing wrong and why i cant make it work, here is the exact things i typed into my pc. i try to run the final make and install vts-backend but they both come up with errors but lets focus on this threads error uptop.


1  sudo apt-get update -y
    2  sudo apt-get install -y dpkg
    3  sudo add-apt-repository ppa:ubuntugis/ppa
    4  sudo apt-get update
    5  sudo apt-get install qgis python-matplotlib python-scipy
    6  sudo apt-get install gdal-bin
    7  sudo apt-get update
    8  sudo apt-get install cmake g++
sudo apt-get install -y libfftw3-dev
sudo apt-get install gfortran

10  sudo apt install git
sudo apt-get install     libboost-dev     libboost-thread-dev     libboost-program-options-dev     libboost-filesystem-dev     libboost-regex-dev     libboost-iostreams-dev    libboost-python-dev     libopencv-dev libopencv-core-dev libopencv-highgui-dev     libopencv-photo-dev libopencv-imgproc-dev libeigen3-dev libgdal-dev     libproj-dev libgeographic-dev libjsoncpp-dev     libprotobuf-dev protobuf-compiler libprocps-dev libmagic-dev     libtinyxml2-dev libmarkdown2-dev     gawk sqlite3



Now 

git clone https://www.graphics.rwth-aachen.de:9000/OpenMesh/OpenMesh.git
cd OpenMesh
mkdir build
cd build
cmake ..
make -j4
sudo make install


cd
Next



git clone --recursive https://github.com/melowntech/vts-mapproxy.git


Configure and build

For building VTS-Mapproxy, you just have to use make

cd vts-mapproxy/mapproxy
make -j4 # to compile in 4 threads

make install DESTDIR=/home/user/tmp/

wget -O - http://cdn.melown.com/packages/keys/oss.packages%40melown.com.key | sudo apt-key add -


cd /etc/apt/sources.list.d/ && sudo wget http://cdn.melown.com/packages/conf/melown-bionic.list

apt update


Next


$ cd /etc/apt/sources.list.d/ && sudo wget http://cdn.melown.com/packages/conf/melown-bionic.list

$ wget -O - http://cdn.melown.com/packages/keys/oss.packages%40melown.com.key | sudo apt-key add -

sudo apt-get update


sudo apt install \
    cmake \
    nasm \
    libssl-dev \
    python-minimal \
    libboost-all-dev \
    libeigen3-dev \
    libproj-dev \
    libgeographic-dev \
    libjsoncpp-dev \
    libsdl2-dev \
    libfreetype6-dev \
    Libharfbuzz-dev
git clone --recursive https://github.com/melowntech/vts-browser-cpp.git
cd vts-browser-cpp/browser
make


sudo apt install vts-backend

**Comment by danammeansbear** [comment]
sorry for blowing up your issues, I am just trying to get this working and am a new developer.

**Comment by malytomas** [comment]
> pc@pc:~/vts-browser-cpp/browser$ make -j4
> 
>     * Building in build
>       CMake Error at cmake/buildsys_initial_validation.cmake:4 (message):
>       CMAKE_BUILD_TYPE is not set.
>       Call Stack (most recent call first):
>       CMakeLists.txt:4 (include)
> 

I see that the build instructions are not updated. Please, use this instead:

```bash
cd vts-browser-cpp/browser
make purge # clear any previous attempts at building
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RELEASE .. # run configure, also set the variable
cmake --build . -- -j4 # this will run the make file (in 4 threads)
```

**Comment by danammeansbear** [comment]
set the variable?
*Adam Dabdoub*
Autonomy Systems Technician
Sensors & Software Systems Division

300 College Park, Dayton, OH 45469-0089
c: 513.886.0301|  udri.udayton.edu <https://www.udayton.edu/udri/>

*University of Dayton Research Institute*

**Comment by malytomas** [comment]
> cmake -DCMAKE_BUILD_TYPE=RELEASE
> CMake Error: The source directory "/home/pc/vts-browser-cpp/browser/build" does not appear to contain CMakeLists.txt. Specify --help for usage, or press the help button on the CMake GUI.

You missed the two dots. That is the path to the folder with CMakeLists.txt.
```bash
cmake -DCMAKE_BUILD_TYPE=RELEASE ..
```

---

> set the variable?
CMAKE_BUILD_TYPE is variable that defines what configuration to use for the build. Valid values are release, debug, relwithdebinfo and minsizerel.

**Comment by malytomas** [comment]
I have updated the build instructions.

**Comment by danammeansbear** [comment]
I will check it out, I appreciate your help and reaching out.
